from mide.replay_errors import (
    REPLAY_ERROR_INVALID_EVIDENCE,
    REPLAY_ERROR_LEGACY_SCAN,
    REPLAY_ERROR_SCAN_NOT_FOUND,
    REPLAY_ERROR_SYMBOL_NOT_FOUND,
)


def test_replay_error_labels_are_stable():
    assert REPLAY_ERROR_INVALID_EVIDENCE == "INVALID_EVIDENCE"
    assert REPLAY_ERROR_LEGACY_SCAN == "LEGACY_SCAN"
    assert REPLAY_ERROR_SCAN_NOT_FOUND == "SCAN_NOT_FOUND"
    assert REPLAY_ERROR_SYMBOL_NOT_FOUND == "SYMBOL_NOT_FOUND"
