"""Stable error labels for Walter replay diagnostics."""

REPLAY_ERROR_INVALID_EVIDENCE = "INVALID_EVIDENCE"
REPLAY_ERROR_LEGACY_SCAN = "LEGACY_SCAN"
REPLAY_ERROR_SCAN_NOT_FOUND = "SCAN_NOT_FOUND"
REPLAY_ERROR_SYMBOL_NOT_FOUND = "SYMBOL_NOT_FOUND"
